backend = "glx";
   vsync = true;
   active-opacity = 0.97;
   inactive-opacity = 0.83;
   frame-opacity = 0.7;

# Радиус скругления (ставим 6, как у бара)
corner-radius = 10;

# Исключения (чтобы не скруглять то, что не нужно)
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

opacity-rule = [
  "100:_NET_WM_STATE@[0]:a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[1]:a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[2]:a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[3]:a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[4]:a = '_NET_WM_STATE_FULLSCREEN'"
];

# unredir-if-possible = true;

# Fading (Плавное появление и исчезновение)
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 5;

fade-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
