# ~/.config/mpv/mpv.conf

# === Удобство ===
save-position-on-quit=yes  # Запоминать позицию воспроизведения при выходе. Маст-хэв!
pause=yes                  # Запускать видео на паузе
keep-open=yes              # Не закрывать плеер после окончания видео
